name: Code Workflow

on:
  push:
    branches:
      - main

jobs:
  code-validation:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node JS
        uses: actions/setup-node@v3
        with:
            node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Check code lint
        uses: npm run lint
        continue-on-error: false

      - name: Review files
        run: ls